# Generated by Django 3.0.5 on 2020-04-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('max_downloads', models.IntegerField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
