# Generated by Django 3.0.6 on 2020-05-25 10:27

from django.db import migrations, models
import upload.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='count_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='delete_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='upload',
            name='download_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[upload.validators.validate_file_size]),
        ),
    ]
